version: '3'

networks: 
  yii2:

services:
  nginx-rest:
    image: nginx:stable-alpine
    container_name: nginx-rest
    ports: 
      - "8088:80"
    volumes: 
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on: 
      - php-rest
      - mysql-rest
    networks: 
      - yii2

  mysql-rest:
    image: mysql:5.7.22
    container_name: mysql-rest
    restart: unless-stopped
    tty: true
    ports: 
      - "4306:3306"
    volumes: 
      - ./mysql:/var/lib/mysql
    environment: 
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks: 
    - yii2

  php-rest:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: php-rest
    volumes: 
      - ./src:/var/www/html
    ports: 
      - "9000:9000"
    networks: 
    - yii2